import { StyleSheet } from 'react-native';

export const onboardingStyles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  screenContent: {
    flex: 1,
    paddingHorizontal: 32,
    paddingVertical: 32,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  welcomeContent: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaWrapper: {
    width: '100%',
    paddingBottom: 24,
  },
  logoWrapper: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 16,
  },
  logoText: {
    fontSize: 28,
    fontFamily: 'Urbanist_700Bold',
    color: '#111',
  },
  heroImage: {
    width: 411,
    height: 411,
    alignSelf: 'center',
  },
  textBlock: {
    width: '100%',
    alignItems: 'center',
    marginVertical: 12,
    maxWidth: 280,
  },
  nameContent: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  nameHeroImage: {
    width: 356,
    height: 356,
    alignSelf: 'center',
    marginTop: 16,
  },
  primaryHeading: {
    fontSize: 36,
    fontFamily: 'Urbanist_700Bold',
    fontWeight: '700',
    color: '#111',
    textAlign: 'center',
  },
  subHeading: {
    fontSize: 16,
    fontFamily: 'Urbanist_500Medium',
    fontWeight: '500',
    color: '#4e4e4e',
    textAlign: 'center',
    marginTop: 8,
  },
  primaryCta: {
    width: '100%',
    backgroundColor: '#cde7f7',
    paddingVertical: 18,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
    marginTop: 16,
    maxWidth: 320,
    alignSelf: 'center',
  },
  primaryCtaText: {
    textAlign: 'center',
    fontSize: 18,
    fontFamily: 'Urbanist_700Bold',
    fontWeight: '700',
    color: '#111',
  },
  nameInput: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 30,
    paddingHorizontal: 24,
    paddingVertical: 16,
    fontSize: 16,
    color: '#111',
    fontFamily: 'Urbanist_400Regular',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
    marginVertical: 16,
    maxWidth: 320,
    alignSelf: 'center',
  },
  dashboardRoot: {
    flex: 1,
    backgroundColor: '#f6f0e9',
  },
  dashboardScrollContent: {
    paddingHorizontal: 0,
    paddingTop: 16,
    paddingBottom: 120,
  },
  dashboardHeaderCard: {
    backgroundColor: '#ffffff',
    borderRadius: 32,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 24,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  dashboardHeaderTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  dashboardDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
  },
  calendarIcon: {
    width: 18,
    height: 18,
    marginRight: 8,
    resizeMode: 'contain',
  },
  dashboardDateText: {
    fontSize: 13,
    fontFamily: 'Urbanist_500Medium',
    color: '#9a8c76',
  },
  settingsIcon: {
    width: 28,
    height: 28,
  },
  dashboardGreeting: {
    marginTop: 4,
    marginHorizontal: 4,
    fontSize: 28,
    fontFamily: 'Urbanist_700Bold',
    color: '#111',
  },
  calendarStrip: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: 18,
  },
  calendarDay: {
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  calendarDayPill: {
    borderRadius: 18,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  calendarDayPillToday: {
    backgroundColor: '#ffffff',
    width: 56,
    height: 56,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  calendarDayLabel: {
    fontSize: 12,
    fontFamily: 'Urbanist_500Medium',
    color: '#bab1a4',
    textAlign: 'center',
  },
  calendarDayLabelToday: {
    color: '#111',
  },
  calendarDayNumber: {
    marginTop: 4,
    fontSize: 16,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#4f463a',
    textAlign: 'center',
  },
  activitiesSection: {
    marginTop: 60,
    paddingHorizontal: 24,
  },
  activitiesHeading: {
    fontSize: 20,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#111',
    marginBottom: 12,
  },
  activitiesList: {
    gap: 3,
  },
  activityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 28,
    paddingVertical: 16,
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    marginBottom: 11,
  },
  activityIconWrapper: {
    width: 64,
    height: 64,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  activityIcon: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
  },
  activityLabel: {
    fontSize: 16,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#4f463a',
  },
  bottomNavContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingBottom: 16,
    paddingHorizontal: 16,
  },
  bottomNavCard: {
    backgroundColor: '#ffffff',
    borderRadius: 32,
    paddingVertical: 16,
    paddingHorizontal: 32,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -4 },
    elevation: 10,
  },
  bottomNavIconWrapper: {
    paddingHorizontal: 8,
  },
  bottomNavIcon: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
  },
  journalScrollContent: {
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 120,
  },
  journalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  journalTitle: {
    fontSize: 36,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#3a2a1a',
  },
  journalSubtitle: {
    marginTop: 6,
    fontSize: 18,
    fontFamily: 'Urbanist_400Regular',
    color: '#af9e8e',
  },
  journalNewButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#4b3422',
    justifyContent: 'center',
    alignItems: 'center',
  },
  journalNewIcon: {
    width: 26,
    height: 26,
    tintColor: '#ffffff',
    resizeMode: 'contain',
  },
  journalSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: 24,
    marginBottom: 16,
  },
  journalSectionTitle: {
    fontSize: 18,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#3a2a1a',
    textAlign: 'left',
    alignSelf: 'flex-start',
  },
  journalEmptyState: {
    marginTop: 40,
    paddingVertical: 32,
    paddingHorizontal: 20,
    borderRadius: 24,
    backgroundColor: '#fdf6ee',
  },
  journalEmptyTitle: {
    fontSize: 18,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#4f3b27',
    marginBottom: 8,
  },
  journalEmptySubtitle: {
    fontSize: 14,
    fontFamily: 'Urbanist_400Regular',
    color: '#a38f7c',
  },
  journalBackButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#4b3422',
    justifyContent: 'center',
    alignItems: 'center',
  },
  journalBackIcon: {
    width: 26,
    height: 26,
    tintColor: '#ffffff',
    resizeMode: 'contain',
  },
  journalTopRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginBottom: 32,
  },
  journalBackLabel: {
    fontSize: 14,
    fontFamily: 'Urbanist_500Medium',
    color: '#4f3b27',
  },
  // New Journal Entry Styles
  newJournalScrollContent: {
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 120,
  },
  newJournalTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 32,
  },
  newJournalTitle: {
    fontSize: 20,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#3a2a1a',
    marginLeft: 16,
  },
  newJournalSection: {
    marginBottom: 28,
  },
  newJournalLabel: {
    fontSize: 14,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#3a2a1a',
    marginBottom: 12,
  },
  newJournalTitleInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  newJournalTitleIcon: {
    width: 20,
    height: 20,
    marginRight: 12,
    resizeMode: 'contain',
  },
  newJournalTitleInput: {
    flex: 1,
    fontSize: 16,
    fontFamily: 'Urbanist_500Medium',
    color: '#3a2a1a',
    padding: 0,
  },
  newJournalEditIcon: {
    width: 20,
    height: 20,
    marginLeft: 12,
    resizeMode: 'contain',
  },
  newJournalTextContainer: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1.5,
    borderColor: '#e0d5c7',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  newJournalTextInput: {
    fontSize: 15,
    fontFamily: 'Urbanist_400Regular',
    color: '#3a2a1a',
    minHeight: 140,
    padding: 0,
    textAlignVertical: 'top',
  },
  newJournalFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#f0ebe5',
  },
  newJournalFooterButton: {
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  newJournalFooterText: {
    fontSize: 18,
    fontFamily: 'Urbanist_400Regular',
    color: '#bab1a4',
  },
  newJournalCharCount: {
    fontSize: 13,
    fontFamily: 'Urbanist_500Medium',
    color: '#9a8c76',
  },
  newJournalCreateButton: {
    flexDirection: 'row',
    backgroundColor: '#4b3422',
    borderRadius: 30,
    paddingVertical: 16,
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
    marginTop: 32,
  },
  newJournalCreateButtonText: {
    fontSize: 16,
    fontFamily: 'Urbanist_700Bold',
    color: '#fff',
    marginRight: 8,
  },
  newJournalCreateCheckmark: {
    width: 20,
    height: 20,
    tintColor: '#fff',
    resizeMode: 'contain',
  },
  journalEntriesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  journalEntryCard: {
    width: '48%',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  journalEntryHeader: {
    marginBottom: 12,
  },
  journalEntryTitle: {
    fontSize: 16,
    fontFamily: 'Urbanist_700Bold',
    color: '#3a2a1a',
    marginBottom: 4,
  },
  journalEntryDate: {
    fontSize: 12,
    fontFamily: 'Urbanist_400Regular',
    color: '#9a8c76',
  },
  journalEntryPreview: {
    fontSize: 13,
    fontFamily: 'Urbanist_400Regular',
    color: '#6b5d50',
    lineHeight: 18,
  },
  journalDetailScrollContent: {
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 120,
  },
  journalDetailTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 32,
  },
  journalDetailDeleteButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#ff6b6b',
    justifyContent: 'center',
    alignItems: 'center',
  },
  journalDetailDeleteIcon: {
    width: 26,
    height: 26,
    tintColor: '#ffffff',
    resizeMode: 'contain',
  },
  journalDetailHeader: {
    marginBottom: 24,
  },
  journalDetailTitle: {
    fontSize: 28,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#3a2a1a',
    marginBottom: 8,
  },
  journalDetailDate: {
    fontSize: 14,
    fontFamily: 'Urbanist_500Medium',
    color: '#9a8c76',
  },
  journalDetailContent: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1.5,
    borderColor: '#e0d5c7',
  },
  journalDetailBody: {
    fontSize: 15,
    fontFamily: 'Urbanist_400Regular',
    color: '#3a2a1a',
    lineHeight: 24,
  },
});

