import { StyleSheet } from 'react-native';

export const onboardingStyles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  screenContent: {
    flex: 1,
    paddingHorizontal: 32,
    paddingVertical: 32,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  welcomeContent: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaWrapper: {
    width: '100%',
    paddingBottom: 24,
  },
  logoWrapper: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 16,
  },
  logoText: {
    fontSize: 28,
    fontFamily: 'Urbanist_700Bold',
    color: '#111',
  },
  heroImage: {
    width: 411,
    height: 411,
    alignSelf: 'center',
  },
  textBlock: {
    width: '100%',
    alignItems: 'center',
    marginVertical: 12,
    maxWidth: 280,
  },
  nameContent: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  nameHeroImage: {
    width: 356,
    height: 356,
    alignSelf: 'center',
    marginTop: 16,
  },
  primaryHeading: {
    fontSize: 36,
    fontFamily: 'Urbanist_700Bold',
    fontWeight: '700',
    color: '#111',
    textAlign: 'center',
  },
  subHeading: {
    fontSize: 16,
    fontFamily: 'Urbanist_500Medium',
    fontWeight: '500',
    color: '#4e4e4e',
    textAlign: 'center',
    marginTop: 8,
  },
  primaryCta: {
    width: '100%',
    backgroundColor: '#cde7f7',
    paddingVertical: 18,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
    marginTop: 16,
    maxWidth: 320,
    alignSelf: 'center',
  },
  primaryCtaText: {
    textAlign: 'center',
    fontSize: 18,
    fontFamily: 'Urbanist_700Bold',
    fontWeight: '700',
    color: '#111',
  },
  nameInput: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 30,
    paddingHorizontal: 24,
    paddingVertical: 16,
    fontSize: 16,
    color: '#111',
    fontFamily: 'Urbanist_400Regular',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
    marginVertical: 16,
    maxWidth: 320,
    alignSelf: 'center',
  },
  dashboardRoot: {
    flex: 1,
    backgroundColor: '#f6f0e9',
  },
  dashboardScrollContent: {
    paddingHorizontal: 0,
    paddingTop: 16,
    paddingBottom: 120,
  },
  dashboardHeaderCard: {
    backgroundColor: '#ffffff',
    borderRadius: 32,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 24,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  dashboardHeaderTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  dashboardDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
  },
  calendarIcon: {
    width: 18,
    height: 18,
    marginRight: 8,
    resizeMode: 'contain',
  },
  dashboardDateText: {
    fontSize: 13,
    fontFamily: 'Urbanist_500Medium',
    color: '#9a8c76',
  },
  settingsIcon: {
    width: 28,
    height: 28,
  },
  dashboardGreeting: {
    marginTop: 4,
    marginHorizontal: 4,
    fontSize: 28,
    fontFamily: 'Urbanist_700Bold',
    color: '#111',
  },
  calendarStrip: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: 18,
  },
  calendarDay: {
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  calendarDayPill: {
    borderRadius: 18,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  calendarDayPillToday: {
    backgroundColor: '#ffffff',
    width: 56,
    height: 56,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  calendarDayLabel: {
    fontSize: 12,
    fontFamily: 'Urbanist_500Medium',
    color: '#bab1a4',
    textAlign: 'center',
  },
  calendarDayLabelToday: {
    color: '#111',
  },
  calendarDayNumber: {
    marginTop: 4,
    fontSize: 16,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#4f463a',
    textAlign: 'center',
  },
  activitiesSection: {
    marginTop: 60,
    paddingHorizontal: 24,
  },
  activitiesHeading: {
    fontSize: 20,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#111',
    marginBottom: 12,
  },
  activitiesList: {
    gap: 3,
  },
  activityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 28,
    paddingVertical: 16,
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    marginBottom: 11,
  },
  activityIconWrapper: {
    width: 64,
    height: 64,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  activityIcon: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
  },
  activityLabel: {
    fontSize: 16,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#4f463a',
  },
  bottomNavContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingBottom: 16,
    paddingHorizontal: 16,
  },
  bottomNavCard: {
    backgroundColor: '#ffffff',
    borderRadius: 32,
    paddingVertical: 16,
    paddingHorizontal: 32,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -4 },
    elevation: 10,
  },
  bottomNavIconWrapper: {
    paddingHorizontal: 8,
  },
  bottomNavIcon: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
  },
  journalScrollContent: {
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 120,
  },
  journalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  journalTitle: {
    fontSize: 36,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#3a2a1a',
  },
  journalSubtitle: {
    marginTop: 6,
    fontSize: 18,
    fontFamily: 'Urbanist_400Regular',
    color: '#af9e8e',
  },
  journalNewButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#4b3422',
    justifyContent: 'center',
    alignItems: 'center',
  },
  journalNewIcon: {
    width: 26,
    height: 26,
    tintColor: '#ffffff',
    resizeMode: 'contain',
  },
  journalSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: 24,
    marginBottom: 16,
  },
  journalSectionTitle: {
    fontSize: 18,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#3a2a1a',
    textAlign: 'left',
    alignSelf: 'flex-start',
  },
  journalEmptyState: {
    marginTop: 40,
    paddingVertical: 32,
    paddingHorizontal: 20,
    borderRadius: 24,
    backgroundColor: '#fdf6ee',
  },
  journalEmptyTitle: {
    fontSize: 18,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#4f3b27',
    marginBottom: 8,
  },
  journalEmptySubtitle: {
    fontSize: 14,
    fontFamily: 'Urbanist_400Regular',
    color: '#a38f7c',
  },
  journalBackButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#4b3422',
    justifyContent: 'center',
    alignItems: 'center',
  },
  journalBackIcon: {
    width: 26,
    height: 26,
    tintColor: '#ffffff',
    resizeMode: 'contain',
  },
  journalTopRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginBottom: 32,
  },
  journalBackLabel: {
    fontSize: 14,
    fontFamily: 'Urbanist_500Medium',
    color: '#4f3b27',
  },
  // New Journal Entry Styles
  newJournalScrollContent: {
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 120,
  },
  newJournalTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 32,
  },
  newJournalTitle: {
    fontSize: 20,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#3a2a1a',
    marginLeft: 16,
  },
  newJournalSection: {
    marginBottom: 28,
  },
  newJournalLabel: {
    fontSize: 14,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#3a2a1a',
    marginBottom: 12,
  },
  newJournalTitleInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  newJournalTitleIcon: {
    width: 20,
    height: 20,
    marginRight: 12,
    resizeMode: 'contain',
  },
  newJournalTitleInput: {
    flex: 1,
    fontSize: 16,
    fontFamily: 'Urbanist_500Medium',
    color: '#3a2a1a',
    padding: 0,
  },
  newJournalEditIcon: {
    width: 20,
    height: 20,
    marginLeft: 12,
    resizeMode: 'contain',
  },
  newJournalTextContainer: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1.5,
    borderColor: '#e0d5c7',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  newJournalTextInput: {
    fontSize: 15,
    fontFamily: 'Urbanist_400Regular',
    color: '#3a2a1a',
    minHeight: 140,
    padding: 0,
    textAlignVertical: 'top',
  },
  newJournalFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#f0ebe5',
  },
  newJournalFooterButton: {
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  newJournalFooterText: {
    fontSize: 18,
    fontFamily: 'Urbanist_400Regular',
    color: '#bab1a4',
  },
  newJournalCharCount: {
    fontSize: 13,
    fontFamily: 'Urbanist_500Medium',
    color: '#9a8c76',
  },
  newJournalCreateButton: {
    flexDirection: 'row',
    backgroundColor: '#4b3422',
    borderRadius: 30,
    paddingVertical: 16,
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
    marginTop: 32,
  },
  newJournalCreateButtonText: {
    fontSize: 16,
    fontFamily: 'Urbanist_700Bold',
    color: '#fff',
    marginRight: 8,
  },
  newJournalCreateCheckmark: {
    width: 20,
    height: 20,
    tintColor: '#fff',
    resizeMode: 'contain',
  },
  journalEntriesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  journalEntryCard: {
    width: '48%',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  journalEntryHeader: {
    marginBottom: 12,
  },
  journalEntryTitle: {
    fontSize: 16,
    fontFamily: 'Urbanist_700Bold',
    color: '#3a2a1a',
    marginBottom: 4,
  },
  journalEntryDate: {
    fontSize: 12,
    fontFamily: 'Urbanist_400Regular',
    color: '#9a8c76',
  },
  journalEntryPreview: {
    fontSize: 13,
    fontFamily: 'Urbanist_400Regular',
    color: '#6b5d50',
    lineHeight: 18,
  },
  journalDetailScrollContent: {
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 120,
  },
  journalDetailTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 32,
  },
  journalDetailDeleteButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#ff6b6b',
    justifyContent: 'center',
    alignItems: 'center',
  },
  journalDetailDeleteIcon: {
    width: 26,
    height: 26,
    tintColor: '#ffffff',
    resizeMode: 'contain',
  },
  journalDetailHeader: {
    marginBottom: 24,
  },
  journalDetailTitle: {
    fontSize: 28,
    fontFamily: 'Urbanist_800ExtraBold',
    color: '#3a2a1a',
    marginBottom: 8,
  },
  journalDetailDate: {
    fontSize: 14,
    fontFamily: 'Urbanist_500Medium',
    color: '#9a8c76',
  },
  journalDetailContent: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1.5,
    borderColor: '#e0d5c7',
  },
  journalDetailBody: {
    fontSize: 15,
    fontFamily: 'Urbanist_400Regular',
    color: '#3a2a1a',
    lineHeight: 24,
  },

  // Breathing Exercises Screen
  breathingScrollContent: {
    paddingHorizontal: 0,
    paddingTop: 16,
    paddingBottom: 120,
  },
  breathingTopRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 24,
    marginBottom: 32,
  },
  breathingTitle: {
    fontSize: 32,
    fontFamily: 'Urbanist_700Bold',
    color: '#3a2a1a',
    textAlign: 'center',
    marginHorizontal: 24,
    marginBottom: 40,
    marginTop: 16,
  },
  breathingCircleContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 32,
    height: 280,
  },
  breathingGradientBase: {
    width: 200,
    height: 200,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  breathingAnimatedCircle: {
    width: 160,
    height: 160,
    borderRadius: 80,
    justifyContent: 'center',
    alignItems: 'center',
  },
  breathingSoundLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 24,
    marginVertical: 20,
  },
  breathingSoundIcon: {
    width: 16,
    height: 16,
    marginRight: 8,
    tintColor: '#9a8c76',
    resizeMode: 'contain',
  },
  breathingSoundText: {
    fontSize: 12,
    fontFamily: 'Urbanist_600SemiBold',
    color: '#9a8c76',
    letterSpacing: 0.5,
  },
  breathingTimeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  breathingTime: {
    fontSize: 14,
    fontFamily: 'Urbanist_500Medium',
    color: '#6b5d50',
  },
  breathingWaveform: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
    height: 80,
    paddingHorizontal: 24,
    marginBottom: 32,
    gap: 4,
  },
  breathingWaveBar: {
    width: 4,
    backgroundColor: '#cde7f7',
    borderRadius: 2,
    flex: 1,
  },
  breathingControls: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    gap: 48,
    marginBottom: 32,
  },
  breathingControlText: {
    fontSize: 32,
    opacity: 0.7,
  },
  breathingPlayButton: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  breathingPlayIcon: {
    fontSize: 32,
    color: '#3a2a1a',
  },
  breathingControlIcon: {
    width: 28,
    height: 28,
    tintColor: '#3a2a1a',
    resizeMode: 'contain',
  },
  breathingPlayImage: {
    width: 32,
    height: 32,
    tintColor: '#3a2a1a',
    resizeMode: 'contain',
  },
  breathingSeekContainer: {
    paddingHorizontal: 24,
    marginBottom: 20,
  },
  breathingSeekTouchable: {
    width: '100%',
  },
  breathingSeekTrack: {
    height: 6,
    backgroundColor: '#e0e0e0',
    borderRadius: 6,
    overflow: 'hidden',
    justifyContent: 'center',
  },
  breathingSeekProgress: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: '#7ba86f',
  },
  breathingSeekThumb: {
    position: 'absolute',
    top: -6,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#7ba86f',
    borderWidth: 0,
  },

  // Resources Screen Styles
  resourcesTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 24,
  },
  resourcesHeaderRow: {
    marginBottom: 24,
  },
  resourcesScrollContent: {
    paddingHorizontal: 24,
    paddingVertical: 24,
  },
  resourcesList: {
    marginBottom: 24,
  },
  resourceCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  resourceIconWrapper: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  resourceIcon: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
    tintColor: '#fff',
  },
  resourceCardContent: {
    flex: 1,
  },
  resourceCardTitle: {
    fontSize: 16,
    fontFamily: 'Urbanist_600SemiBold',
    color: '#3a2a1a',
    marginBottom: 4,
  },
  resourceCardDescription: {
    fontSize: 13,
    fontFamily: 'Urbanist_400Regular',
    color: '#999',
  },
  resourceArrow: {
    fontSize: 18,
    fontFamily: 'Urbanist_600SemiBold',
    color: '#ccc',
    marginLeft: 8,
  },
  resourcesFooter: {
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 24,
  },
  resourcesFooterText: {
    fontSize: 12,
    fontFamily: 'Urbanist_400Regular',
    color: '#666',
    lineHeight: 18,
  },

  // Crisis Support Screen Styles
  crisisTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 24,
  },
  crisisHeaderRow: {
    marginBottom: 24,
  },
  crisisScrollContent: {
    paddingHorizontal: 24,
    paddingVertical: 24,
  },
  crisisServicesList: {
    marginBottom: 24,
  },
  crisisServiceCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  crisisServiceIconWrapper: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  crisisServiceIcon: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
    tintColor: '#fff',
  },
  crisisServiceContent: {
    flex: 1,
  },
  crisisServiceName: {
    fontSize: 16,
    fontFamily: 'Urbanist_700Bold',
    color: '#3a2a1a',
    marginBottom: 4,
  },
  crisisServiceDescription: {
    fontSize: 13,
    fontFamily: 'Urbanist_400Regular',
    color: '#999',
    marginBottom: 8,
  },
  crisisServicePhone: {
    fontSize: 14,
    fontFamily: 'Urbanist_600SemiBold',
    color: '#3a2a1a',
    marginBottom: 4,
  },
  crisisServiceAvailability: {
    fontSize: 12,
    fontFamily: 'Urbanist_400Regular',
    color: '#ccc',
  },
  crisisReminder: {
    backgroundColor: '#e8f5e9',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 24,
  },
  crisisReminderTitle: {
    fontSize: 14,
    fontFamily: 'Urbanist_700Bold',
    color: '#2e7d32',
    marginBottom: 8,
  },
  crisisReminderText: {
    fontSize: 13,
    fontFamily: 'Urbanist_400Regular',
    color: '#558b2f',
    lineHeight: 20,
  },

  // Analytics Screen Styles
  analyticsTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 24,
  },
  analyticsHeaderRow: {
    marginBottom: 32,
  },
  analyticsScrollContent: {
    paddingHorizontal: 24,
    paddingVertical: 24,
  },
  analyticsEmptyState: {
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingVertical: 48,
    paddingHorizontal: 24,
    alignItems: 'center',
    marginBottom: 24,
  },
  analyticsEmptyIcon: {
    fontSize: 64,
    marginBottom: 16,
  },
  analyticsEmptyIconText: {
    fontSize: 64,
  },
  analyticsEmptyTitle: {
    fontSize: 20,
    fontFamily: 'Urbanist_700Bold',
    color: '#3a2a1a',
    marginBottom: 8,
  },
  analyticsEmptySubtitle: {
    fontSize: 14,
    fontFamily: 'Urbanist_400Regular',
    color: '#999',
    textAlign: 'center',
    lineHeight: 20,
  },
  analyticsStatsPreview: {
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  analyticsPreviewTitle: {
    fontSize: 14,
    fontFamily: 'Urbanist_600SemiBold',
    color: '#3a2a1a',
    marginBottom: 16,
  },
  analyticsStat: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#efe9df',
  },
  analyticsStatLabel: {
    fontSize: 14,
    fontFamily: 'Urbanist_500Medium',
    color: '#666',
  },
  analyticsStatValue: {
    fontSize: 18,
    fontFamily: 'Urbanist_700Bold',
    color: '#4b3422',
  },

  // Mood Tracking Screen Styles
  moodTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 24,
  },
  moodHeaderRow: {
    marginBottom: 32,
  },
  moodScrollContent: {
    paddingHorizontal: 24,
    paddingVertical: 24,
  },
  moodSelector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    marginBottom: 32,
    gap: 12,
  },
  moodOption: {
    width: '18%',
    paddingVertical: 16,
    paddingHorizontal: 8,
    borderRadius: 14,
    backgroundColor: '#f5f5f5',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  moodEmoji: {
    fontSize: 32,
    marginBottom: 6,
  },
  moodLabel: {
    fontSize: 11,
    fontFamily: 'Urbanist_600SemiBold',
    color: '#666',
    textAlign: 'center',
  },
  moodLabelSelected: {
    color: '#fff',
  },
  moodNoteContainer: {
    marginBottom: 24,
  },
  moodNoteLabel: {
    fontSize: 14,
    fontFamily: 'Urbanist_600SemiBold',
    color: '#3a2a1a',
    marginBottom: 10,
  },
  moodNoteInput: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#efe9df',
    paddingHorizontal: 16,
    paddingVertical: 16,
    minHeight: 100,
    justifyContent: 'flex-start',
  },
  moodNotePlaceholder: {
    fontSize: 14,
    fontFamily: 'Urbanist_400Regular',
    color: '#ccc',
  },
  moodSaveButton: {
    backgroundColor: '#4b3422',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 24,
  },
  moodSaveButtonDisabled: {
    backgroundColor: '#d9d9d9',
  },
  moodSaveButtonText: {
    fontSize: 16,
    fontFamily: 'Urbanist_700Bold',
    color: '#fff',
  },
  moodTip: {
    backgroundColor: '#fef5e7',
    borderLeftWidth: 4,
    borderLeftColor: '#f39c12',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 24,
  },
  moodTipTitle: {
    fontSize: 14,
    fontFamily: 'Urbanist_700Bold',
    color: '#3a2a1a',
    marginBottom: 6,
  },
  moodTipText: {
    fontSize: 13,
    fontFamily: 'Urbanist_400Regular',
    color: '#666',
    lineHeight: 18,
  },

  // Mood Tracking Full Screen Styles
  moodGradientContainer: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  moodFullScreenContent: {
    flex: 1,
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 20,
    paddingBottom: 40,
  },
  moodCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginLeft: 24,
  },
  moodCloseButtonText: {
    fontSize: 24,
    color: '#fff',
    fontWeight: '700',
  },
  moodFullScreenQuestion: {
    fontSize: 32,
    fontFamily: 'Urbanist_700Bold',
    color: '#fff',
    textAlign: 'center',
    paddingHorizontal: 24,
    marginTop: 40,
    marginBottom: 60,
  },
  moodFullScreenIcon: {
    width: 120,
    height: 120,
    resizeMode: 'contain',
    marginBottom: 40,
  },
  moodFullScreenLabel: {
    fontSize: 24,
    fontFamily: 'Urbanist_600SemiBold',
    color: '#fff',
    marginBottom: 60,
  },
  moodFullScreenArrows: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 40,
    marginBottom: 40,
  },
  moodArrowText: {
    fontSize: 40,
    color: 'rgba(255, 255, 255, 0.8)',
    fontFamily: 'Urbanist_700Bold',
  },
  moodSetButton: {
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 32,
    minWidth: 180,
  },
  moodSetButtonText: {
    fontSize: 16,
    fontFamily: 'Urbanist_700Bold',
    color: '#3a2a1a',
    textAlign: 'center',
  },

  // Mood Selection Grid Styles
  moodOptionIcon: {
    width: 32,
    height: 32,
    resizeMode: 'contain',
    marginBottom: 4,
  },

  // Analytics Mood Logs Styles
  analyticsMoodLogsSection: {
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 20,
    marginTop: 16,
  },
  analyticsMoodLogsTitle: {
    fontSize: 14,
    fontFamily: 'Urbanist_600SemiBold',
    color: '#3a2a1a',
    marginBottom: 12,
  },
  analyticsMoodLogItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#efe9df',
  },
  analyticsMoodLogColor: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 12,
  },
  analyticsMoodLogContent: {
    flex: 1,
  },
  analyticsMoodLogLabel: {
    fontSize: 14,
    fontFamily: 'Urbanist_600SemiBold',
    color: '#3a2a1a',
  },
  analyticsMoodLogDate: {
    fontSize: 12,
    fontFamily: 'Urbanist_400Regular',
    color: '#999',
    marginTop: 2,
  },
  calmSoundsContainer: {
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  calmSoundCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  calmSoundIconBox: {
    width: 50,
    height: 50,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  calmSoundIcon: {
    width: 24,
    height: 24,
    tintColor: '#fff',
  },
  calmSoundTextBox: {
    flex: 1,
  },
  calmSoundName: {
    fontSize: 16,
    fontFamily: 'Urbanist_600SemiBold',
    color: '#111',
  },
  calmSoundDescription: {
    fontSize: 12,
    fontFamily: 'Urbanist_400Regular',
    color: '#999',
    marginTop: 4,
  },
  calmSoundArrow: {
    width: 20,
    height: 20,
    transform: [{ rotate: '180deg' }],
  },
});


